// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAqq54CgAKQ7K7oH8B97dxpHM6XBkcFo4',
    appId: '1:391164186968:web:0b6dce556321b3034ad52d',
    messagingSenderId: '391164186968',
    projectId: 'kutuphane-otomasyon-8df39',
    authDomain: 'kutuphane-otomasyon-8df39.firebaseapp.com',
    storageBucket: 'kutuphane-otomasyon-8df39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSQGe-8sEZHwfkAoBbe_e1Uvz96hPgm6U',
    appId: '1:391164186968:android:46d23470b7ef54514ad52d',
    messagingSenderId: '391164186968',
    projectId: 'kutuphane-otomasyon-8df39',
    storageBucket: 'kutuphane-otomasyon-8df39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUKJsxoVj9__ljVBWFnZ9num0KNp7mNnA',
    appId: '1:391164186968:ios:e4a1824df38db5d24ad52d',
    messagingSenderId: '391164186968',
    projectId: 'kutuphane-otomasyon-8df39',
    storageBucket: 'kutuphane-otomasyon-8df39.appspot.com',
    iosBundleId: 'com.example.kutuphaneOtomasyon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUKJsxoVj9__ljVBWFnZ9num0KNp7mNnA',
    appId: '1:391164186968:ios:074e777c72c583294ad52d',
    messagingSenderId: '391164186968',
    projectId: 'kutuphane-otomasyon-8df39',
    storageBucket: 'kutuphane-otomasyon-8df39.appspot.com',
    iosBundleId: 'com.example.kutuphaneOtomasyon.RunnerTests',
  );
}
